name: Deploy Version

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  version_up:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Get latest milestone
        id: milestone
        uses: actions/github-script@v7
        with:
          script: |
            const pulls = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  base: 'main',
                  state: 'closed',
                  sort: 'updated',
                  direction: 'desc',
                  per_page: 1
            });
            const lastPR = pulls.data.find(pr => pr.merged_at);

            core.setOutput('id', lastPR?.milestone?.number);
            core.setOutput('title',  lastPR?.milestone?.title);
            core.setOutput('version',  (lastPR?.milestone?.title || '').replace('v', ''));
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Milestone
        run: |
          echo "Milestone ID: ${{ steps.milestone.outputs.id }}"
          echo "Milestone Title: ${{ steps.milestone.outputs.title }}"
          echo "Milestone Version: ${{ steps.milestone.outputs.version }}"

      - name: Get Package Version
        id: package_version
        uses: actions/github-script@v7
        with:
          script: |
            const pkg = require('./package.json');
            core.setOutput('currentVersion', pkg.version);

      - name: Bump version in package.json
        uses: actions/github-script@v7
        if: steps.package_version.outputs.currentVersion != steps.milestone.outputs.version
        with:
          script: |
            const pkg = require('./package.json');
            pkg.version = '${{ steps.milestone.outputs.version }}';
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));

      - name: Configurar Git
        if: steps.package_version.outputs.currentVersion != steps.milestone.outputs.version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump

        if: steps.package_version.outputs.currentVersion != steps.milestone.outputs.version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="bump/v${{ steps.milestone.outputs.version }}"
          git checkout -b $VERSION
          git add .
          git commit -m "chore: bump version to $(node -p "require('./package.json').version") by github-actions[bot]"
          git push origin $VERSION
          gh pr create --title "chore: bump version to $(node -p "require('./package.json').version")" --body "Automated version bump" --base main --head $VERSION
          gh pr merge $VERSION --squash --delete-branch

      - name: Close milestone
        if: success()
        run: |
          gh api \
            -X PATCH \
            repos/${{ github.repository }}/milestones/${{ steps.milestone.outputs.id }} \
            -f state=closed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
